In [1]:
# 배열 만들기

list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
import numpy as np 

np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
print(np.array([3,1.4,2,3,4.5]))

# 넘파이의 array는 단일 데이터 타입 (하나의 데이터 타입만 갖는)
# 정수, 실수 >> 실수로 변경됨

[3.  1.4 2.  3.  4.5]


In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [14]:
print(np.array([1,2,3,4]))
print()
print(np.array([1,2,3,4], dtype=float))
# dtype 옵션 : data type 명시

print()
arr = np.array([1,2,3,4], dtype=float)
print(arr)
print(arr.dtype)

# astype() : 데이터 타입 변경
print(arr.astype(int))

[1 2 3 4]

[1. 2. 3. 4.]

[1. 2. 3. 4.]
float64
[1 2 3 4]


In [15]:
# np.zeros()
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
# np.ones()
np.ones((3,5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
# np.arange(start, stop, step)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
# np.linspace() : n-bbang
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
# 난수 활용, 배열 만들기

np.random.random((2,2))
# 0~1 사이 균일 분포 난수 생성
# (2,2) : size >> 튜플형태로 매개변수로 받아서 난수 생성

array([[0.98878155, 0.10231419],
       [0.0794023 , 0.20520262]])

In [21]:
# 도와주세요.

# np.random.random이 np.random.rand 하고 같은건가요?

np.random.rand(2,2)
# 0~1 사이 균일 분포 난수 생성
# 직접 차원(2,2) 인수 넣어줌

array([[0.33457756, 0.55710059],
       [0.57121437, 0.86733253]])

In [27]:
np.random.normal(0, 1, (2,2)) 
# normal(평균, 표준편차, 매개변수(튜플))
# 정규분포 형태, 매개변수를 튜플로 받아서 난수 생성

array([[ 1.28692349, -0.1918155 ],
       [ 0.45575198, -2.01334826]])

In [23]:
np.random.randn(2,2)
# 2*2 크기의 배열을 직접 생성

array([[-1.42083968, -0.51512022],
       [-0.01365035,  0.24446363]])

In [28]:
np.random.randint(0,10,(2,2))
# 0~9(n-1)까지   숫자 범위에서 
# 정수로 이루어진 (2,2) 행렬 생성  

array([[7, 8],
       [3, 2]])

In [29]:
# 배열의 기초

np.random.randint(10, size = (3,4))
# 10 : 최대값, 명시 안하면 최소값 0

array([[4, 4, 6, 3],
       [8, 5, 4, 0],
       [1, 4, 3, 3]])

In [32]:
x = np.random.randint(10, size = (3,4))

print(x.ndim) # 2 : 2차원
print(x.shape) # (3,4) 행렬 ( 형태)
print(x.size) # 12 >> 크기(원소의 개수)
print(x.dtype) # int32 (정수) 데이터 타입

2
(3, 4)
12
int32


In [33]:
# indexing 과 slicing

np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [36]:
# indexing

a = np.arange(7)

print(a[3])
print(a[-3])

3
4


In [37]:
a[0] = 10
print(a)

[10  1  2  3  4  5  6]


In [40]:
# slicing

print(a)
print()
print(a[1:4])
print()
print(a[1:])
print()
print(a[::2]) # interval이 2칸씩
print(a[::-1]) # 역순 출력 (***)

[10  1  2  3  4  5  6]

[1 2 3]

[1 2 3 4 5 6]

[10  2  4  6]
[ 6  5  4  3  2  1 10]


In [46]:
# reshape (형태 변경) (****)

x = np.arange(8)
print(x)
print()

print(x.shape) # 1차원 (8개 원속)
print()

x2 = x.reshape(2,4) # 2차원 (2,4) 행렬로 변환
print(x2)
print(x2.shape)

[0 1 2 3 4 5 6 7]

(8,)

[[0 1 2 3]
 [4 5 6 7]]
(2, 4)


In [50]:
# 이어 붙이고 나누기 작업

# 이어 붙이기 >> concatenate : array 이어 붙임

x1 = np.array([0,1,2])
x2 = np.array([3,4,5])

print(x1)
print()
print(x2)
print()

print(np.concatenate([x1,x2]))

[0 1 2]

[3 4 5]

[0 1 2 3 4 5]


In [56]:
# concatenate >> axis 축 기준 이어 붙이기

m = np.arange(4).reshape(2,2)

print(m)
print()
print(np.concatenate([m,m]))
print()
print(np.concatenate([m,m], axis=0))
# axis=0 (default, 설정된 기본값)

print()
print(np.concatenate([m,m], axis=1))


[[0 1]
 [2 3]]

[[0 1]
 [2 3]
 [0 1]
 [2 3]]

[[0 1]
 [2 3]
 [0 1]
 [2 3]]

[[0 1 0 1]
 [2 3 2 3]]


In [68]:
# 나누기(split)
np.arange(16).reshape(4,4)

m = np.arange(16).reshape(4,4)
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [69]:
print(np.split(m, [3], axis=0))

[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [72]:
m1, m2 = np.split(m, [3], axis=0)

print(m1)
print()
print(m2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]]


In [70]:
print(np.split(m,[3], axis=1))

[array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [73]:
m3, m4 = np.split(m,[3], axis=1)

print(m3)
print()
print(m4)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]

[[ 3]
 [ 7]
 [11]
 [15]]


넘파이 연산

In [81]:
# array 의 모든 원소에 5를 더하는 함수 생성

def 더하기_5(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = values[i] + 5
    return output


values = np.random.randint(1, 10, size=5)

print(values)
print(더하기_5(values))
        

[3 7 6 2 7]
[ 8. 12. 11.  7. 12.]


In [84]:
# loop vs numpy

big_arr = values = np.random.randint(1, 10, size=1000000)

더하기_5(big_arr)

array([13.,  8., 14., ..., 11.,  9., 14.])

In [85]:
big_arr + 5 # broadcasting 되어 계산 >> 헐. 훨씬 빠르네

array([13,  8, 14, ..., 11,  9, 14])

In [75]:
np.empty(5)
# 5개의 우너소를 가진 1차원 배열 생성 
# 초기화는 되어 있지 않음
# > 여기에 출력되는 값은 메모리에 이미 존재한 임의의 값으로 배열 채움

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [86]:
# 기본 연산

np.arange(4)

array([0, 1, 2, 3])

In [88]:
x = np.arange(4)

print(x + 5)
print(x - 5)
print(x * 5)
print(x / 5)

[5 6 7 8]
[-5 -4 -3 -2]
[ 0  5 10 15]
[0.  0.2 0.4 0.6]


In [92]:
# 행렬 간 연산

x = np.arange(4).reshape((2,2))
y =np.random.randint(10, size = (2,2))


print(x+y)
print()
print(x-y)

[[ 8  2]
 [ 3 12]]

[[-8  0]
 [ 1 -6]]


In [95]:
# 브로드캐스팅 (BroadCasting)

print(x)
print()
print(x+5)

[[0 1]
 [2 3]]

[[5 6]
 [7 8]]


In [97]:
# 집계함수

np.arange(8).reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [99]:
x = np.arange(8).reshape((2,4))

print(np.sum(x))
print(np.min(x))
print(np.max(x))
print(np.mean(x))

28
0
7
3.5


In [102]:
# axis 사용, 집계하기

print(x)
print()
print(np.sum(x, axis=0))
print()
print(np.sum(x, axis=1))

[[0 1 2 3]
 [4 5 6 7]]

[ 4  6  8 10]

[ 6 22]


In [103]:
# 마스킹(masking) 연산 (조건 연산자 >> True, False)

np.arange(5)

array([0, 1, 2, 3, 4])

In [104]:
x = np.arange(5)

print(x<3)
print()
print(x>5)

[ True  True  True False False]

[False False False False False]


In [105]:
x[x<3]

array([0, 1, 2])

In [106]:
condition = (x<3)

x[condition]

array([0, 1, 2])